<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ian</AssemblyName>
    <RootNamespace>IanLang</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Version>0.6.0</Version>
    <Description>i@N Language - Unified Runtime</Description>
  </PropertyGroup>
  <ItemGroup>
    <!-- Backups antiguos: quedan en disco pero no compilan -->
    <Compile Remove="ian_brain_v022.cs" />
  </ItemGroup>
</Project>
